linters:
  enable:
  - errcheck
  - gofmt
  - gocritic
  - goimports
  - gosec
  - misspell
  - revive
  - unused
inters-settings:
  revive:
    ignore-generated-header: true
    rules:
      - name: blank-imports
        disabled: true

output:
  uniq-by-line: false

run:
  issues-exit-code: 1
  timeout: 5m
