name: Code linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  # allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ${{ format('{0}-{1}', join(fromJSON('["base","dind","2204"]'), '-'), matrix.arch) }}
    strategy:
      matrix:
        arch: [ amd64 ]
        build-type: [release]
      fail-fast: false
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display Go version
      run: |
        go version

    - name: Install vaccel
      run: |
       wget https://s3.nbfc.io/nbfc-assets/github/vaccel/rev/main/x86_64/release/vaccel_latest_amd64.deb && sudo dpkg -i vaccel_latest_amd64.deb && rm vaccel_latest_amd64.deb && sudo ldconfig
       
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      env:
              PKG_CONFIG_PATH: /usr/local/share
      with:
          version: v1.64

          # show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true


